Dynamic/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :skills

  resources :educations

  resources :experiences

  resources :users

  resources :resumes

  resources :postings

  resources :companies

  root 'welcome#index'

end

Dynamic/app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :resume
  belongs_to :user
end

Dynamic/app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  # GET /experiences
  # GET /experiences.json
  def index
    @experiences = Experience.all
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1
  # PATCH/PUT /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: 'Experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
      params.require(:experience).permit(:postition, :start_date, :end_date, :description, :rank)
    end
end

Dynamic/app/helpers/experiences_helper.rb
module ExperiencesHelper
end

Dynamic/app/views/experiences/_form.html.erb
<%= form_for(@experience) do |f| %>
  <% if @experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% @experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :postition %><br>
    <%= f.text_field :postition %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.text_field :end_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Dynamic/app/views/experiences/edit.html.erb
<h1>Editing experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', experiences_path %>

Dynamic/app/views/experiences/index.html.erb
<h1>Listing experiences</h1>

<table>
  <thead>
    <tr>
      <th>Postition</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Description</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiences.each do |experience| %>
      <tr>
        <td><%= experience.postition %></td>
        <td><%= experience.start_date %></td>
        <td><%= experience.end_date %></td>
        <td><%= experience.description %></td>
        <td><%= experience.rank %></td>
        <td><%= link_to 'Show', experience %></td>
        <td><%= link_to 'Edit', edit_experience_path(experience) %></td>
        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experience', new_experience_path %>

Dynamic/app/views/experiences/new.html.erb
<h1>New experience</h1>

<%= render 'form' %>

<%= link_to 'Back', experiences_path %>

Dynamic/app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Postition:</strong>
  <%= @experience.postition %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @experience.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @experience.end_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @experience.description %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @experience.rank %>
</p>

<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>