Dynamic/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :skills

  resources :educations

  resources :experiences

  resources :users

  resources :resumes

  resources :postings

  resources :companies

  root 'welcome#index'

end

Dynamic/app/models/posting.rb
class Posting < ActiveRecord::Base
  belongs_to :company
  has_many :resumes
end

Dynamic/app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  before_action :set_posting, only: [:show, :edit, :update, :destroy]

  # GET /postings
  # GET /postings.json
  def index
    @postings = Posting.all
  end

  # GET /postings/1
  # GET /postings/1.json
  def show
  end

  # GET /postings/new
  def new
    @posting = Posting.new
  end

  # GET /postings/1/edit
  def edit
  end

  # POST /postings
  # POST /postings.json
  def create
    @posting = Posting.new(posting_params)

    respond_to do |format|
      if @posting.save
        format.html { redirect_to @posting, notice: 'Posting was successfully created.' }
        format.json { render :show, status: :created, location: @posting }
      else
        format.html { render :new }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postings/1
  # PATCH/PUT /postings/1.json
  def update
    respond_to do |format|
      if @posting.update(posting_params)
        format.html { redirect_to @posting, notice: 'Posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @posting }
      else
        format.html { render :edit }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
  def destroy
    @posting.destroy
    respond_to do |format|
      format.html { redirect_to postings_url, notice: 'Posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posting
      @posting = Posting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def posting_params
      params.require(:posting).permit(:skills, :description, :experience, :postition)
    end
end

Dynamic/app/helpers/postings_helper.rb
module PostingsHelper
end

Dynamic/app/views/postings/_form.html.erb
<%= form_for(@posting) do |f| %>
  <% if @posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@posting.errors.count, "error") %> prohibited this posting from being saved:</h2>

      <ul>
      <% @posting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :skills %><br>
    <%= f.text_field :skills %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.text_field :experience %>
  </div>
  <div class="field">
    <%= f.label :postition %><br>
    <%= f.text_field :postition %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Dynamic/app/views/postings/edit.html.erb
<h1>Editing posting</h1>

<%= render 'form' %>

<%= link_to 'Show', @posting %> |
<%= link_to 'Back', postings_path %>

Dynamic/app/views/postings/index.html.erb
<h1>Listing postings</h1>

<table>
  <thead>
    <tr>
      <th>Skills</th>
      <th>Description</th>
      <th>Experience</th>
      <th>Postition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postings.each do |posting| %>
      <tr>
        <td><%= posting.skills %></td>
        <td><%= posting.description %></td>
        <td><%= posting.experience %></td>
        <td><%= posting.postition %></td>
        <td><%= link_to 'Show', posting %></td>
        <td><%= link_to 'Edit', edit_posting_path(posting) %></td>
        <td><%= link_to 'Destroy', posting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Posting', new_posting_path %>

Dynamic/app/views/postings/new.html.erb
<h1>New posting</h1>

<%= render 'form' %>

<%= link_to 'Back', postings_path %>

Dynamic/app/views/postings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Skills:</strong>
  <%= @posting.skills %>
</p>

<p>
  <strong>Description:</strong>
  <%= @posting.description %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @posting.experience %>
</p>

<p>
  <strong>Postition:</strong>
  <%= @posting.postition %>
</p>

<%= link_to 'Edit', edit_posting_path(@posting) %> |
<%= link_to 'Back', postings_path %>